### PR TITLE
fix get_animal_characteristics interface

### PR DESCRIPTION
**Pull request by trevis-dev**
Evaluator expects to receive animal attributes in another order (2 occurrences).

### CODE REVIEW

**Comment by xshitaka** [comment]
In my opinion it would be more logical to switch the characteristics order in the evaluator contract, instead of the exercise solution interface.

To keep the interface coherent, you would also need to edit the `declare_animal` method

**Comment by trevis-dev** [comment]
That way would need redeployment of the evaluator..

I was considering the evaluator as defining the specs for a "test-driven development", and the interface as a help, but that may not be the right approach.

To be honest, I guess I would suggest an alphabetical order if redeployment is involved 😅

**Comment by xshitaka** [comment]
I've found another issue in the evaluator (ex5b: instead of checking if the evaluator is a breeder, the check is made on the caller address), I'll make a pull request to fix it, thus the Evaluator needs to be redeployed anyway 😅

**Comment by trevis-dev** [comment]
Also thinking it'd be best if both are updated, I'm closing this in favor of #5, which links to this for reference to your upcoming PR, @xshitaka

**Comment by l-henri** [comment]
PR 5 merged

**Pull request closed without merging**
